name: Simulator CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: install Python dependencies
      run: pip install pandas numpy

    - name: compile Simulator
      run: gcc -O3 -fopenmp simulator.c -o simulator -lm

    - name: run Simulation
      run: ./simulator 0.1 0.25 100 1000 0 "data/nodes.csv" "data/edges.csv" > actual_output.csv

    - name: validate results
      run: python test/ci_validate.py
      
